bakery:
  allowMissingPackageInstallation: true
  baseUrl: http://rosco-alias:8087
  extractBuildDetails: true
  propagateCloudProviderType: true
default:
  bake:
    account: minikube
  securityGroups: null
  vpc:
    securityGroups: null
echo:
  baseUrl: 8089
  enabled: false
flex:
  baseUrl: http://not-a-host
front50:
  baseUrl: http://front50-alias:8080
igor:
  enabled: true
  baseUrl: http://igor-alias:8088
kato:
  baseUrl: http://clouddriver-alias:7002
mort:
  baseUrl: http://clouddriver-alias:7002
oort:
  baseUrl: http://clouddriver-alias:7002
redis:
  connection: redis://redis-alias:6379
server:
  port: 8083
services:
  orca:
    timezone: west
tasks:
  executionWindow:
    timezone: west
tide:
  baseUrl: http://not-a-host
  enabled: false
